jae-hun-e/LocoMoco

- src/app/chat/_components/review/Profile.tsx
- src/app/chat/_components/review/Rating.tsx
- src/app/chat/_components/review/Review.tsx
- src/app/chat/_components/review/ReviewContent.tsx
- src/app/chat/_components/review/StarList.tsx
- 후기 ui 구현
- 유효성 검사
- 모달이 완성되면 내용만 옮기면 되도록 Review.tsx컴포넌트에 제작했습니다.
close #26
> [#26] 후기 모달 UI

- src/app/chat/[id]/page.tsx
- src/app/chat/[id]/participants/page.tsx
- 채팅방 UI를 작업했습니다.
- 참여자 목록 간단하게 만들었습니다.
내용이 모두 동일한 것을 더미데이터를 넣었기 때문입니다.
- 채팅기능을 만들면서 지속적으로 UI도 수정해나가겠습니다. 
- package.json과 yarn.lock을 login-api에서 PR해버리는 실수를 하였습니다. 
혹시 login-api merge이전에 테스트 해보실때는
yarn add sockjs-client @stomp/stompjs
yarn add -D @types/sockjs-client
한번씩 해주시면 감사하겠습니다. 죄송합니다.
- Login-api가 이미 합쳐진 상태라면 안하셔도 됩니다.
close #35
> [#35] 채팅방 UI 제작

- src/apis/core.ts
> 타입가드로 window객체 있을 시만 localStorage 접근 하도록 수정
```tsx
axiosInstance.interceptors.request.use(
(config) => {
...
if (typeof window !== 'undefined') {
const token = localStorage.getItem('token');
if (token) config.headers['Authorization'] = `Bearer ${token}`;
}
return config;
},
(error) => {
return Promise.reject(error);
},
);
```
close #58
> [#58] 서버에서 localStorage 접근으로 인해 에러 발생

- src/apis/mgc/useGetMGCDetail.ts
- src/app/_components/Provider.tsx
- src/app/mgc/[id]/MGCPage.tsx
- src/app/mgc/[id]/page.tsx
원인: Suspense를 걸어주면서 SSR렌더링이 걸림
임시: SSR 꺼주는 설정으로 2번 데이터 패칭 막음 (작동 방식 이해가 안됨)
추후 작동 방식의 차이를 이해하고 근본적 해결 필요
close #64
> [#64] 조회수 중복 증가 및 server client 데이터 불일치 에러 임시 해결

- src/app/_components/UserInfoAndButton/UserList.tsx
- src/app/_components/UserInfoAndButton/UserListItem.tsx
- src/app/chat/[id]/participants/page.tsx
- src/app/mypage/black-list/page.tsx
- 공통 컴포넌트 UserInfoAndButton을 생성했습니다. (채팅 참여자 목록, 블랙리스트에서 사용)
- 공통 컴포넌트를 사용하는 방식으로 채팅 참여자 목록을 수정했습니다.
- 블랙리스트 UI를 구현했습니다.
- 헤더를 추가하는 게 좋을 것 같습니다.
close #57
> [#57] 마이페이지 블랙리스트 UI

- src/app/_components/MapCustomControl.tsx
- src/app/create/_components/MGCMap.tsx
- src/app/create/_components/RequiredFields.tsx
- src/app/create/page.tsx
- src/app/layout.tsx
- src/hooks/useCreateKakaoMap.ts
- 유경님이 만들어 주신 지도 hook을 이용해 지도를 연결하고 검색 할 수 있게 구현
- 유저가 클릭한 위치 정보와 동 정보를 사용하여 모각코 생성
1. 버튼에서 이동할 때 뿐만 아니라 롱클릭으로 이동시에는 클릭한 위치정보를 받아와야해서 롱 클릭시 넘겨주는 값이 필요합니다! 
2. zoonIn, Zoonout 시 지도 변경 오류가 나요ㅜㅜ (유경님 헬프,,)
close #76
> [#76] 모각코 생성에 지도 연결

- src/apis/blacklist/useDeleteBlacklist.ts
- src/apis/blacklist/useGetBlacklist.ts
- src/app/_components/UserInfoAndButton/UserList.tsx
- src/app/_components/UserInfoAndButton/UserListItem.tsx
- src/app/chat/[id]/participants/page.tsx
- src/app/mypage/black-list/page.tsx
- 마이페이지 블랙리스트의 API를 연결했습니다.
- `차단 해제` 버튼 클릭 시 해당 사용자가 블랙리스트에서 해제됩니다.
https://github.com/jae-hun-e/LocoMoco/assets/62047243/8a812b18-9bd6-4790-9c8e-597d057150ac
close #73
> [#73] 마이페이지 블랙리스트 API 연결

- src/apis/mgc/useGetMGCDetail.ts
- src/app/_components/header/HeaderLeft.tsx
- src/app/mgc/[id]/MGCPage.tsx
- src/app/mgc/[id]/_components/MGCApplyArea.tsx
- src/app/mgc/[id]/_hooks/useApplyMGC.ts
- src/app/mgc/[id]/_hooks/useIsApply.ts
- src/components/MainStyleButton.tsx
- src/constants/routeURL.ts
- src/hooks/useCreateKakaoMap.ts
- src/utils/getQueryOptions.tsx
- 로그인 시 
- userId로 참여하기 / 톡방 연결 
- userId로 참여하면 모각코, 참여여부 데이터 최신화(현재 캐시값을 무효화시킴)
- 비 로그인 시 
- toast 메시지와 로그인페이지로 이동
빠른 개발을 위해 코드가 조금 지저분 합니다ㅠㅠ 15일까지 MVP완성 후에 리팩 하겠습니다!! 
close #81
> [#81 ] 모각코 디테일 페이지에 참여하기와 톡방 연결 

- src/app/chat/[id]/page.tsx
- src/app/chat/_components/Message.tsx
- src/app/chat/_components/Messages.tsx
- src/app/chat/_components/NotMessage.tsx
- src/app/mgc/[id]/_components/MGCApplyArea.tsx
- 모각코id에 대응하는 채팅방id로 입장
- 채팅방 리팩토링
close #101
> [#101] 모각코별 다른 채팅방 들어가기

- src/app/create/_components/CreateMGC.tsx
- 롱클릭 시 생성된 위치 기본값에 추가
close #124
> [#124] 일반 모각코 생성 시 롱클릭시 모각코 생성 위치 표시

- src/app/_components/MGCList/MGCListItem.tsx
- src/app/chat/_components/Message.tsx
- src/app/mypage/page.tsx
- 채팅 시간 표시 수정
- 마이페이지 cursor-pointer 일관적이지 않은 문제 수정
- 모각코 리스트 제목에 cursor-pointer
close #130
> [#130] 시간 표시 오류

- src/app/mgc/[id]/_components/MGCApplyArea.tsx
- src/app/mypage/(sub-page)/change-my-info/page.tsx
- 모각코 디테일 참여하기 분기처리
- 개인정부 수정 path undefined값 처리 
close #132
> [#132] 모각코 디테일 qa반영

- next.config.mjs
- src/app/mgc/[id]/_components/MGCApplyArea.tsx
- src/app/mypage/(sub-page)/change-my-info/page.tsx
- next.config.mjs 수정 
close #135
> [#135] pwa를 위한 next config 수정

- src/app/_components/CreateBtn.tsx
- 로그인 했는지 인식 못하는 문제수정 로그인해도 모각코 생성 버튼이 안보이는문제
- token에 값을 할당안하는 실수로 인하여 발생한것
close #136
> fix: token allocation

- src/app/chat/_components/Message.tsx
- src/app/chat/page.tsx
- 채팅방 목록, 채팅방 프로필 사진의 비율이 정사각형이 아닌 문제 수정
- 오전, 오후 -> AM, PM
close #141
> [#141] 이미지 비율 조정

- src/apis/review/useGetSentReviewSummary.ts
- 보낸 리뷰페이지의 후기 프로필 리뷰 받은 사람의 프로필로 변경
close #143
> [#143] 보낸 리뷰페이지의 후기 프로필 리뷰 받은 사람의 프로필로 변경

- src/app/_components/filter/FilterContent.tsx
- src/app/_components/filter/TypeCheckList.tsx
- 필터 카테고리 중 "전체" 카테고리 제거
close #146
> [#146] 필터 카테고리 중 "전체" 카테고리 제거

- src/app/chat/_components/review/ReviewContent.tsx
- src/app/mypage/received-reviews-assessment/page.tsx
- 고정 userId에서 로컬스토리지에 저장된 값으로 변경
- 리뷰컨텐츠 api 연결
close #148
> [#148] 더미데이터값 실제값으로 변경

- src/app/(home)/_components/Map.tsx
- src/styles/globals.css
- 모바일 지도에서 롱프레스시 선택되는 문제 해결
- 원인: 이미지 선택시 기본 동작으로 선택이 발생
- 해결: 선택을 막는 css 사용
- 해결 전
- 해결 후
close #154
> [#154] 모바일에서 지도 롱프레스시 SVG 요소가 선택되는 문제 해결

- src/app/(home)/_components/HomeMap.tsx
- src/app/(home)/_components/HomeMapViewer.tsx
- src/app/(home)/_components/MapSection.tsx
- src/app/(home)/_components/SearchBarFilter.tsx
- src/app/(home)/page.tsx
- src/app/_components/Map/Clusterer.tsx
- src/app/_components/Map/Geocoder.tsx
- src/app/_components/Map/Map.tsx
- src/app/_components/Map/MapProvider.tsx
- src/app/_components/Map/MapViewer.tsx
- src/app/_components/Map/Marker.tsx
- src/app/_components/Map/Markers.tsx
- src/app/_components/infoWindow/InfoWindow.tsx
- src/app/layout.tsx
- src/hooks/useChangeMapCenter.ts
- src/hooks/useGetAddressByCoordinates.ts
- src/store/useKakaoMapLoad.ts
- src/store/useSearchValueStore.ts
- 한번만 로드하기 위해 루트레이아웃에 카카오 지도를 로드하는 MapProvider컴포넌트 추가했습니다.
MapProvider.tsx
```
const { setIsLoad } = useKakaoMapLoad();
useEffect(() => {
window.kakao.maps.load(function () {
setIsLoad(true);
});
}, [setIsLoad]);
return <>{children}</>;
```
커다란 커스텀훅이 담당했던 기능들을 컴포넌트별로 기능을 담당하게 함으로써 재사용성과 유지보수성을 개선했습니다.
다음과 같은 이유들로 provider패턴을 적용하게 되었습니다.
1. prop-drilling 방지
2. 각 컴포넌트가 필요로 하는 값에 맞게 서로 다른 값을 제공 가능
- 지도마다 지도 객체에 렌더되는 마커, 등록되는 이벤트등이 다르므로 서로 다른 값을 제공 가능하게 해줄 필요가 있었습니다.
- 수정전
Home.tsx
```
const {
clusterer,
map,
mapRef,
createMarker,
changeCenter,
removeMarker,
movePosition,
isLoad,
getAddressByCoorinates,
} = useCreateKakaoMap({ isCustomlevelControl: false, handleMouseUp: handleMouseUp });
const renderMarker = useRenderMarkerByData(openBottomSheetAndUpdate, handleMouseUp);
return (
<>
<Map …
```
> [#163] 지도 커스텀훅 커스텀화 리팩토링

- src/app/(auth)/signup/[method]/page.tsx
- src/app/api/fcm/route.ts
- src/app/api/fcm/sendFCM.ts
- src/app/mgc/[id]/_components/MGCApplyArea.tsx
- src/app/mypage/page.tsx
- src/hooks/useRequestPermission.ts
- src/hooks/useSaveTokenToDB.ts
- pwa 권한 허용
- pwa 기능
- 
- 아직 알림이 가지 않는 문제있음 원인 알아보는중
close #168
> [#168] PWA 기능 추가

- package.json
- src/app/_components/GoogleAnalyticsTracker.tsx
- src/app/layout.tsx
- src/app/mgc/[id]/_components/MGCApplyArea.tsx
- src/libs/gtag.ts
- tsconfig.json
- yarn.lock
- google analytics 연동
- event 등록하면 좋을 거 같은 부분이 있다면 의견남겨주세요~~
close #191
> [#191] google analytics 연동

- src/hooks/useGeolocation.ts
- 안드로이드 카카오 웹브라우저에서 지도 렌더 오류 해결
-  위치 권한 요청 시 오류 발생하여 예외처리 구문 추가로 해결
close #205
> [#205] 안드로이드 카카오 웹브라우저에서 지도 렌더 오류 해결

- src/apis/core.ts
- 모든 api 요청에 provider 헤더 추가
close #224
> feat: 모든 API 요청에 provider 헤더 추가

- src/app/_components/Map/MapLoaderProvider.tsx
- 중복 지도 로드를 방지하도록 isLoad 조건 추가
close #226
> [#226] 중복 지도 로드를 방지하도록 isLoad 조건 추가

- README.md
- 변경된 디자인 캡쳐본으로 리드미에 첨부한 이미지 변경
> 변경된 디자인 캡쳐본으로 리드미에 첨부한 이미지 변경

- src/app/(auth)/redirect/[method]/page.tsx
- src/app/_components/Provider.tsx
- src/app/chat/page.tsx
[#230 ] 안읽은 메세지와 갱신 토큰 기능 추가
- 안 읽은 메세지 표시 기능
- 갱신 토큰
- 현재 안 읽은 메세지 기능이 갱신되지 않는 문제 있음 백엔드의 수정과 함께 고칠 예정
close #230
> [Feat] 안읽은 메세지와 토큰 
