jae-hun-e/LocoMoco

- src/app/(home)/_components/Map.tsx
- src/app/(home)/_components/MapSection.tsx
- src/hooks/useCreateKakaoMap.ts
- src/hooks/useRenderMarkerByData.ts
- 롱클릭시 마지막 클릭위치로 생성되는 문제 해결
- 원인: 카카오맵에서 동작되지 않는 이벤트를 등록(mouseup, touchend) 및 이벤트 발생 순서 문제
- 해결: 이벤트 변경
- 클러스터 클릭 시 오류 해결
- 원인: 필터결과값이 undefined경우도 객체속성을 이용하려 해서 data가 없다는 오류 발생
- 해결: 필터값 삽입 대신 if문으로 비교후 삽입으로 변경
- 마커클릭 시 마커위치에 위치표시 마커가 생성되는 버그 해결
- 원인: 지도클릭 후 마커 클릭 이벤트가 발생해 map의 click이벤트가 일어나지 않음
- 해결: 마커 클릭 이벤트 발생 시 clearTimeout
- 롱클릭
- 롱프레스
- 클러스터 클릭
- 마커클릭
- 버그 하나당  pr을 날리면 단위가 작은 거 같아서 묶어서 했습니다. 그런데 여러개를 묶는 것이 pr만 보고 확인하기 어려운거 같아 버그 하나당 1개씩 날리는 게 좋을지 고민입니다!! 여러분들은 어떤 게 더 좋으신가요??
close #47
> [#47] kakao map 클릭 이벤트 관련 버그 및 오류 해결

- src/app/mypage/report-list/_components/ReportList.tsx
- src/app/mypage/report-list/_components/ReportListItem.tsx
- src/app/mypage/report-list/page.tsx
- 신고 목록 UI 구현
- 디자인에 추가할 게 있는지 궁금합니다
- 백엔드와 논의 후 신고 대상 닉네임이나 프로필이미지도 보이도록 개선 예정입니다.
close #61
> [#61] 마이페이지 신고목록 UI 구현

- src/app/_components/reviewList/ReviewDetail.tsx
- src/app/_components/reviewList/ReviewItem.tsx
- src/app/_components/reviewList/ReviewList.tsx
- src/app/_components/reviewList/UserInfo.tsx
- src/app/chat/_components/review/StarList.tsx
- src/app/mypage/end-join-mgc/received-reviews/page.tsx
- src/app/mypage/end-join-mgc/send-reviews/page.tsx
- src/types/review.ts
- tailwind.config.ts
- 두페이지 공통 컴포넌트 제작
- 각 페이지 ui 구현
- 리뷰 클릭시 해당 리뷰 내용을 모달에 표시
디자인적으로 수정할 게 있다면 언제든 말씀해주세요~~!!
- 리뷰 페이지
- 리뷰 클릭 시 모달 켜진 화면
- 색상 변수 main-4와 main-5 사이의 색상이 필요해서 추가했습니다! 원래 main-5였던 색상은 main-6으로 수정했습니다.
- 헤더는 재훈님의 pr 내용처럼 mypage/(sub_page)/layout.tsx에 추가할지, 각 페이지의 layout.tsx에 추가할지 정한 후 추가하겠습니다!
- 프로필 부분 ui가 유사한 게 많아서 추후에 합성컴포넌트로 리팩토링 하겠습니다!
- 헤더를 mypage/(sub_page)/layout.tsx에 추가하는 법, 각 페이지의 layout.tsx에 추가하는 법 어떤 게 더 좋을까요??
- 이런식으로 화면을 다 채우는 모달도 괜찮을 거 같은데 팀원분들은 어떤 게 더 좋을거 같은지 궁금합니다!!
close #63
> [#63] 보낸리뷰, 받은리뷰 페이지 ui 구현

- .gitignore
- src/app/_components/header/HeaderLeft.tsx
- src/app/mypage/(sub-page)/_components/MGCSummaryInfo.tsx
- src/app/mypage/(sub-page)/_components/button/ChattingButton.tsx
- src/app/mypage/(sub-page)/_components/button/LikeMGCAreaButtons.tsx
- src/app/mypage/(sub-page)/_components/button/ReviewButtons.tsx
- src/app/mypage/(sub-page)/current-join-mgc/page.tsx
- src/app/mypage/(sub-page)/end-join-mgc/page.tsx
- src/app/mypage/(sub-page)/layout.tsx
- src/app/mypage/(sub-page)/like-mgc/page.tsx
- src/app/mypage/current-join-mgc/page.tsx
- src/app/mypage/end-join-mgc/page.tsx
- src/app/mypage/like-mgc/page.tsx
- src/constants/routeURL.ts
- 마이페이지 내에 모각코 페이지들이 비슷한 속성을 가지고 있어서 합성컴포넌트로 구현했습니다.
- 내부에 공유하는 상태값이 있을 것이라 예상했지만 없었어서 아쉽게 context로 상태를 공유하는 로직은 없습니다. 
- summary 부분이 공통으로 들어가고 각 페이지 특성에 맞게 추가 버튼을 합성하였습니다. 
내가 찜한 모각코
참여중인 모각코
종료된 모각코
찜하기 부분에서 찜 취소를 버튼 vs 하트모양 으로할지 고민입니다.
1. 버튼 -> 안 이쁜데 한 번 더 생각하게 됨
2. 하트모양 -> 이쁜데 취소누르기 너무 쉬워보임
그리고 찜 취소 후 모각코 리스트를 낙관적 업데이트 할지도 고민입니다. 뭔가 취소눌렀다가 다시 찜하는 사람도 있을 것 같아서,,, 
- 합성된 부분에 필요한게 MGC id라고 생각했는데 이것은 실제 API 연결 이후 변경될 수 있습니다. 
close #52
> [#52] 마이페이지 내부 모각코관련 세부페이지 UI 구현

- src/apis/core.ts
- src/app/(auth)/redirect/[method]/page.tsx
- src/app/(auth)/signin/page.tsx
- src/app/(auth)/signup/[method]/page.tsx
- src/app/(auth)/signup/_components/DatePick.tsx
- src/app/(auth)/signup/_components/ProgressBar.tsx
- src/app/_components/Modal.tsx
- src/utils/storage.ts
- 로그인과 회원가입을 하기전에 redirection 페이지를 거쳐서 분기시킴
- 로그인한 유저의 로그인/회원가입 페이지 접근 제한
- useClickAway를 이용하여 번객모각코 생성모달 닫게 하기
깃허브는 회원가입을 하지않았고 카카오톡은 회원가입을 한 상태입니다.
https://github.com/jae-hun-e/LocoMoco/assets/96977881/fb21a4d3-bad8-4627-9338-7f8dad65297f
- 지금 경고같은것을 alert를 이용해서 하고 있는데 공통적으로 사용하는 모달이 있으면 좋겠다는 생각을 했어요.
close #68
> [#68] 로그인/회원가입 로직 변경

- src/apis/core.ts
- src/apis/mgcList/useMGCTotalList.ts
- src/app/(home)/_components/MapSection.tsx
- src/app/(home)/page.tsx
- src/app/_components/filter/Filter.tsx
- src/app/_components/filter/FilterContent.tsx
- src/app/_components/filter/TypeCheckList.tsx
- src/app/layout.tsx
- src/hooks/useCreateKakaoMap.ts
- src/store/useSearchValueStore.ts
- 필터 카테고리 api 연동 후 서버 값으로 변경
- 수정된 api에 맞춰서 검색 기능 구현
- 태그 + 동명을 관리하는 전역 상태 생성하여 관리
-  고정된 params값에서 사용자가 입력 or 선택한 값으로 api 호출
- `useCreateKakaoMap.ts`에 동명을 받아오는 함수을 추가했습니다. 모각코 생성시에 이 함수를 활용해서 동명을 받아오면 됩니다!
```
const getAddressByCoorinates = useCallback(
async (latitude: number, longitude: number) => {
try {
const addressName = await coord2RegionCodePromise(longitude, latitude);
return addressName;
} catch (error) {
console.error(error);
return;
}
},
[coord2RegionCodePromise],
);
```
close #70
> [#70] 홈페이지 동명검색 및 필터 사용자 입력 적용

- src/app/mypage/(sub-page)/_components/button/LikeMGCAreaButtons.tsx
- src/app/mypage/(sub-page)/current-join-mgc/_hooks/useGetCurrentJoinMGC.ts
- src/app/mypage/(sub-page)/current-join-mgc/page.tsx
- src/app/mypage/(sub-page)/end-join-mgc/_hooks/useGetEndMGC.ts
- src/app/mypage/(sub-page)/end-join-mgc/page.tsx
- src/app/mypage/(sub-page)/like-mgc/_hooks/useGetLikeMGC.ts
- src/app/mypage/(sub-page)/like-mgc/page.tsx
- src/app/mypage/_components/UserInfo.tsx
- src/app/mypage/_hooks/useMypageInfo.ts
- src/app/mypage/page.tsx
- 각각의 마이페이지에 모각코 API만 연결을 한 상태입니다.
- 이 중 BE와 협의가 필요한부분이 생겨 작업이 중지되었습니다.
mypage detail에 각각 모각코 정보의 개수를 담아서 주는 거라면 숫자를 띄워줄 수 있지만 
모든 정보를 넘겨받아 length로 몇개인지를 띄우는 거라면 mypage에서 보여주는 정보에 비해 가지고 있는 정보가 많습니다.(로딩이 오래걸려집니다.)
1. 찜한, 참여중인, 종료된 모각코 개수의 정보가 중요한게 아니라면 마이페이지에서 보여주지 않는 방법 
2. 중요한 정보라면 mypage detail API 내에 개수만 담아서 받아오는 방법
이 둘중 고민 중입니다. 
- BE와 논의 사항
- 현재 찜하기는 MGCSummary 타입 형태로 데이터가 넘어오지만 진행 중, 종료된 모각코는 MGCDetail 타입 형태로 데이터가 넘어옵니다.
- 미리보기에는 필요없는 데이터들이므로 MGCSummary로 변경을 요청드릴 예정입니다.
close #89
> [#89 ] 마이페이지 내 모각코페이지들 API연결

- src/apis/report/useDeleteReportList.ts
- src/apis/report/useGetReportList.ts
- src/apis/report/useModifyReportList.ts
- src/app/mypage/report-list/_components/ReportList.tsx
- src/app/mypage/report-list/_components/ReportListItem.tsx
- src/app/mypage/report-list/_components/ReportModifyModal.tsx
- src/app/mypage/report-list/page.tsx
- src/types/report.ts
- 마이페이지의 신고 목록의 API를 연결했습니다.
- 신고 목록 가져오기, 수정, 삭제가 가능합니다.
https://github.com/jae-hun-e/LocoMoco/assets/62047243/acd08075-89e1-403a-8b07-c06d8390ce37
- 수정 버튼 클릭 시 띄워진 모달의 textarea에 자동으로 focus가 가게 하고싶은데.. react hook form의 setFocus가 적용되질 않네요
close #79
> [#79] 마이페이지 신고 목록 API 연결

- src/app/(auth)/signup/[method]/page.tsx
- src/app/(auth)/signup/_components/DatePick.tsx
- src/app/(auth)/signup/_components/Gender.tsx
- src/app/(auth)/signup/_components/Job.tsx
- src/app/(auth)/signup/_components/Nickname.tsx
- src/app/mypage/(sub-page)/change-my-info/page.tsx
- src/app/mypage/page.tsx
- src/types/userInfo.ts
- 공통으로 사용되는 UserProfile type분리
- 로그아웃 깃허브/카카오 
- 회원탈퇴
- 회원가입 페이지에서 새로고침시 토큰이 없어져서 새로고침시 로그인 화면으로 돌려보냄
생략
close #82
> [#82] 로그아웃/회원탈퇴

- src/apis/review/useGetReceivedReviewSummary.ts
- src/apis/review/useGetSentReviewSummary.ts
- src/apis/user/queryFn.ts
- src/apis/user/useGetJoinMGCByUserId.ts
- src/apis/user/useGetUserInfo.ts
- src/app/_components/MGCList/MGCList.tsx
- src/app/_components/UserProfileInfo.tsx
- src/app/another/[userId]/(main)/page.tsx
- src/app/another/[userId]/join-mgc/page.tsx
- src/app/chat/[id]/loading.tsx
- src/app/chat/_components/review/Review.tsx
- src/app/mypage/page.tsx
- src/constants/mypageDummyData.ts
- 다른 유저 상세 페이지 api 연결
- 유저 정보 api 연결
- 유저가 참여한 모각코 api 연결
- 유저 페이지
- 모각코 리스트를 여러곳에서 사용하기에 빈값일 때 안내문구를 "해당하는 모각코가 없습니다!" 로 변경했습니다. 문구를 각각 다르게 할지 이렇게 하나로 할지 여러분들은 어떤 게 더 좋으신가요??
- 현재 더미값을 넣어둬서 더미값이 떴다가 실제 값으로 변경되는데 추후에 스켈레톤 ui를 적용하고 수정하겠습니다!
- UserInfo의 타입을 서버에서 오는 것과 같이 변경했습니다.
- 종료된 모각코, 참여중인 모각코를 합쳐서 `참여한 모각코`를 만들었습니다. 이 과정에서 종료된 모각코 api, 참여중인 모각코 api 는 다른 곳에서 쓰일 것이기에 `queryFn.ts` 파일에 따로 빼뒀습니다
apis/user/queryFn.ts
```
export const getOngoingMGCByUserId = async (userId: string) => {
return client.get<MGCSummary[]>({
url: `users/${userId}/mogakko/ongoing`,
});
};
export const getCompleteMGCByUserId = async (userId: string) => {
return client.get<MGCSummary[]>({
url: `users/${userId}/mogakko/complete`,
});
};
```
close #87
> [#87] 다른 유저 상세 페이지 api 연결

- src/apis/review/useCreateReview.ts
- src/app/_components/Modal.tsx
- src/app/_components/header/Header.tsx
- src/app/_components/header/MenuBtn.tsx
- src/app/chat/[id]/page.tsx
- src/app/chat/_components/review/Review.tsx
- src/app/chat/layout.tsx
- 각 톡방페이지에서 해당 참여자 목록 모달 토글
- Menu 컴포넌트를 버튼 컴포넌트로 변경
- 참여자 목록에서 후기 작성 화면으로 전환
- isUserList 값을 토대로 참여자 목록과 후기화면 전환
- 현재는 chatPage에서 chatId를 params로 받아오는데 그렇게하면 모각코 참여리스트를 위한 MGCId값을 구하기 위한 api를 또 사용해야 합니다. 그래서 params를 `모각코 id를 받아오는 것으로 가정하고 작업했는데 이 방법 어떠신가요??
- `UserList.tsx`에서 data의 길이가 0일때 "신고 목록이 없습니다"라는 멘트는 한곳에서만 사용가능한 멘트라서 바꿔야할 거 같아서 아래 두가지 방법 중 어떤 방법이 좋을까요??
1. 공통되는 멘트로 바꾼다 (ex: 해당 사용자가 존재하지 않습니다)
2. props로 멘트를 받아온다
close #94
> [#94] 채팅 페이지 내 참여 목록 및 후기 작성을 위한 모달 기능 추가

- next.config.mjs
- src/app/_components/header/Header.tsx
- src/app/_components/header/HeaderLeft.tsx
- src/app/mgc/[id]/_components/Inquiry.tsx
- src/app/mgc/[id]/_components/MGCApplyArea.tsx
- src/app/mypage/page.tsx
- src/constants/routeURL.ts
1. 비회원 마이페이지 접근시 로그인 페이지로 이동
2. 헤더 css 변경
3. 외부이미지 경로 next.config설정
close #111
> [#111] 비회원 처리 + 외부 이미지 설정 추가

- src/apis/thunderMGC/useCreateThunderMGC.ts
- src/app/(home)/_components/ThunderModal/ThunderModal.tsx
- 번개 모각코 tag를 추가해서 번개 모각코일 경우 번개 아이콘이 제목 앞에 붙도록 했습니다.
- 이제 모각코 생성 시 디테일 페이지로 이동합니다. 
close #116
> [#116] 번개 모각코 tag 추가 및 생성 시 디테일 페이지로 이동

- src/apis/review/useGetReceivedReviewSummary.ts
- src/apis/review/useGetSentReviewSummary.ts
- src/apis/user/useGetUserInfo.ts
- src/app/_components/ProfileImg.tsx
- src/app/_components/UserInfoAndButton/UserListItem.tsx
- src/app/_components/UserProfileInfo.tsx
- src/app/_components/reviewList/ReviewItem.tsx
- src/app/_components/reviewList/UserInfo.tsx
- src/app/another/[userId]/(main)/error.tsx
- src/app/another/[userId]/(main)/loading.tsx
- src/app/another/[userId]/(main)/page.tsx
- src/app/chat/_components/Message.tsx
- src/app/chat/_components/review/Profile.tsx
- src/app/chat/_components/review/Review.tsx
- src/app/mgc/[id]/_components/AuthorInfo.tsx
- src/app/mgc/[id]/_components/MGCParticipants.tsx
- src/constants/mypageDummyData.ts
- src/types/review.ts
- 유저 페이지 연결
- 존재하지 않는 유저페이지 접근 시 처리
-  suspense처리를 해서 없는 경우 바로 에러를 띄우고 error.tsx에서 잡는 식으로 구현했습니다.
- 존재하지 않는 사용자 화면
- 에러처리에 관한 ui가 정해지지 않아 임시로 안내글만 적어뒀습니다.
- 일단 프로필 이미지가 있는 부분을 다 연결해 두었는데 추가로 연결할 부분이 있다면 알려주세요!
- 현재 모달을 켜고 끄는 변수를 하나의 store에 저장해두기 때문에 a페이지에서 모달이 켜져있는 상태에서 b 페이지로 이동 시 b페이지의 모달이 켜져있는 버그가 발생합니다. 
- 모달을 제어하는 기능을 hook으로 빼서 ui따로 해당 모달을 제어하는 기능따로 하면 해결 될 거 같습니다!
close #137
> [#137] 유저 페이지 연결 및 존재하지 않는 유저 처리

- src/app/(home)/_components/Map.tsx
- 모바일에서 인포윈도우 닫을 시  닫힘 버튼 위치로 이동되는 문제 해결
- 원인: 닫힘 버튼의 아이콘도 SVGElement라서 지도를 누른것과 같은 동작이 발생
- 해결: 모달안의 요소를 선택하지 못하도록 수정
- 해결 전
- 해결 후
close #156
> [#156] 모바일에서 인포윈도우 닫을 시  닫힘 버튼 위치로 이동되는 문제 해결

- src/app/create/_components/CreateMGC.tsx
- src/app/mgc/[id]/MGCPage.tsx
- src/app/mgc/[id]/_components/MGCApplyArea.tsx
- 모각코 수정시 리스트에서 사라지는 문제 해결
- 원인: 모각코 디테일의 기본값에서 deadline값이 startTime으로 잘못 지정
- 해결: deadline 기본값을 startTime에서 endTime으로 변경
- 마감기한이 지난 모각코도 종료된 모각코로 처리
close #161
> [#161] 모각코 수정시 리스트에서 사라지는 문제 해결

- src/apis/address/useAddressSearch.ts
- src/app/(home)/_components/AddressList.tsx
- src/app/(home)/_components/SearchBarFilter.tsx
- src/constants/metroGovernments.ts
- src/constants/searchResultAddressList.ts
- src/tests/SearchBarFilter.spec.tsx
- 검색 선택 시 해당 값을 search키워드에 넣도록 수정
- search키워드가 없을 시 쿼리가 자동으로 실행되지 않게 수정
- 디바운스를 통해 검색 시 불필요한 api 요청 줄이기
```
const handleKeywordChange = (e: React.ChangeEvent<HTMLInputElement>) => {
const value = e.target.value;
if (typingTimer.current) {
clearTimeout(typingTimer.current);
}
typingTimer.current = setTimeout(() => {
setKeyword(value);
}, 500);
};
```
close #179
> [#179] 검색 기능 수정

- src/app/_components/Map/MGCMap.tsx
- src/app/create/_components/CreateMGC.tsx
- src/app/create/_components/CreateMGCMapViewer.tsx
- src/app/create/_components/MGCTime.tsx
- src/app/create/_components/RequiredFields.tsx
- 유효하지 않은 종료 시간 선택 후 유효한 값으로 수정해도 경고 메시지가 떠있는 버그 해결
- state로 관리되던 에러메시지 대신 register를 등록하고 validate를 추가하여 해결
```
<Input
id={startId}
type="time"
step="600"
{...register('startTime', {
validate: () => validateTimes('start'),
})}
className="w-100pxr text-xs"
defaultValue={watch('startTime')}
/>
```
- 종료 시간을 앞당길 때 발생하는 생성 오류 수정
- deadLine보다 늦은 시간일 시 발생하기에 기본값을 받아올때 00시00분으로 설정하여 해결 
- 생성 페이지에서 기본 위치값이 받아와지지 않는 문제 해결
- 기본 주소가 없다면(=생성 페이지라면) 현재 위치로 값을 설정하여 해결
- 신청마감일 먼저 선택 시 모각코 날짜보다 뒤의 날짜도 선택 가능한 버그 해결
- useEffect로 watch로 잡은 값이 변할 때마다 validate함수를 실행시켜서 해결
- 경고 메시지 UI 겹침 현상 수정
- ui 수정 전
- ui 수정 후
close #181
> [#181] 모각코 생성시 버그 수정

- src/app/(home)/_components/SearchBarFilter.tsx
- src/app/(home)/page.tsx
- src/app/_components/filter/Filter.tsx
- src/constants/geocodeAddressConversion.ts
- src/constants/mswPath.ts
- src/libs/test/mockZustandStore.tsx
- src/libs/test/render.tsx
- src/mocks/handlers.ts
- src/mocks/response/addressList.json
- src/mocks/response/mgcList.json
- src/store/useSearchValueStore.ts
- src/tests/CreateBtn.spec.tsx
- src/tests/Filter.spec.tsx
- src/tests/Home.spec.tsx
- src/tests/SearchBarFilter.spec.tsx
- 홈페이지 통합테스트 작성
- 사용자 입력에 따른 마커들 렌더 테스트
- 필터 컴포넌트 테스트 작성
- 검색 기능 버그 수정
- 광역자치단체가 아닌 주소 검색 시 변환 과정이 필요해서 추가
- 필터 기능 버그 수정
- useMGCTotalList의 매개변수에 tags가 누락되어 있어 추가
사용자의 입력에 따른 마커 렌더 테스트를 하던 중 반복되는 동작에 대해 고민이 생겼습니다.
1. 검색어 입력시 나타나는 마커테스트
2. 필터 선택시 나타나는 마커테스트
3. 검색어 입력 + 필터 선택 시 마커테스트
이렇게 `단계별로 동작들이 더해지는 테스트`를 다하다보니 `중복되는 동작이 많았고` 모두 테스트 할 시 3번만 할때보다 `1초가량 차이`가 났습니다. 그래서 모든 동작을 하는 것보다 앞서 실행되는 작은 단위의 테스트를 추가하고 3번만 하는 방법을 생각했습니다. 
사용자 입력시 마커들이 나타나는 과정은 다음과 같습니다.
사용자 입력 -> 전역상태 변경 -> useQuery 실행 -> Marker컴포넌트의 props로 넘겨줄 값 변경
전역상태가 잘 변경된다면 후속 작업들이 잘될거라 생각하여 검색어입력과 필터 선택시 `전역상태 변경 테스트`를 추가하고 3번 테스트만 작성했습니다. 
- 모든 경우를 테스트하는 방법
- 장점: 테스트 코드의 신뢰도가 높아집니다.
- 단점: 반복되는 동작으로 인해 테스트 시간이 길어집니다.
- 최종동작만 테스트하고 전역상태가 변경되는 테스트를 추가하는 방법
- 장점: 앞의 경우보다 테스트 시간이 줄어듭니다.
- 단점: …
> [#183] 홈페이지 통합테스트

- src/app/(home)/_components/HomeMapViewer.tsx
- src/app/_components/Map/ClustererProvider.tsx
- src/app/_components/Map/GeocoderProvider.tsx
- src/app/_components/Map/MapProvider.tsx
- src/app/_components/Map/Marker.tsx
- src/app/_components/Map/Markers.tsx
- src/app/_components/infoWindow/InfoWindow.tsx
- src/app/create/_components/CreateMGCMapViewer.tsx
- src/hooks/useChangeMapCenter.ts
- src/hooks/useGetAddressByCoordinates.ts
- src/libs/kakaoMapWrapper.ts
- src/tests/Home.spec.tsx
- 카카오 맵 api 기능을 래핑한 클래스 생성
- 해당 클래스를 이용하는 것으로 변경
- 전역 객체 모킹에서 클래스 모킹으로 변경
외부 api를 테스트시 모킹관련 자료를 찾아보다 [Please don't mock me](https://www.youtube.com/watch?v=x8sKpJwq6lY)라는 자료를 봤습니다. 이 발표에서는 외부 API를 직접 모킹하는 대신, 이를 래핑한 클래스를 모킹할 것을 권장하고 있습니다. 
1. 모킹이 쉬워진다.
1. 외부 api와의 응집도를 낮춰 api 변경시 대응에 편리하다.
2. 만약 지도api를 변경할 때 래핑한 클래스의 내용만 변경하면 된다.
이 세가지의 장점을 보고 리팩토링을 결심했습니다. 하지만 모킹 측면에서는 생각보다 많은 이점을 느끼지 못했습니다. (실제로 코드가 5줄 줄었습니다............................😇)
그래도 전역 객체를 모킹할 때는 사용되는 모든 것을 모킹해줘야 하는 반면, 래핑 클래스를 모킹할 때는 몇몇 부분을 생략할 수 있었습니다. 모킹 양에 관한 이점에 대해서는 다른 부분들도 테스트해보고 최종 판단을 내릴 수 있을 것 같습니다!
1. 모킹이 쉬워진다.
⇒ 단위 테스트가 아닌 통합테스트인 home테스트에서는 모킹이 많이 필요해서 대단한 효과는 체감하지 못했습니다.
2. 외부 api와의 응집도를 낮춰 api 변경시 대응에 편리하다.
⇒ 21년도가 마지막 업데이트라 다소 안정된 api라서 변경이 일어날 가능성이 적습니다.
3. 만약 지도api를 변경할 때 …
> [#190] 카카오맵 래핑 클래스 생성 및 적용

- src/libs/test/mockWindowUtils.ts
- src/tests/Home.spec.tsx
- src/tests/SearchBarFilter.spec.tsx
- src/tests/useGeolocation.spec.tsx
- beforeEahc로 초기화 하는 파일에서 setup함수 생성 및 적용
- window.navigator 모킹 유틸함수화 및 적용
close #220
> [#220] 테스트 초기화 방식을 beforeEach에서 setup 함수로 전환 및 모킹 코드 유틸리티화
